// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObservatorioApi.Data;

#nullable disable

namespace ObservatorioApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702051331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObservatorioApi.Models.Deputado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCamara")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeEleitoral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiglaPartido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiglaUf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCamara")
                        .IsUnique();

                    b.ToTable("Deputados");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataDoc")
                        .HasColumnType("date");

                    b.Property<int>("DeputadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDespesa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("ObservatorioApi.Models.PerfilAnalise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeputadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoId")
                        .IsUnique();

                    b.ToTable("PerfisAnalise");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Despesa", b =>
                {
                    b.HasOne("ObservatorioApi.Models.Deputado", "Deputado")
                        .WithMany("Despesas")
                        .HasForeignKey("DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("ObservatorioApi.Models.PerfilAnalise", b =>
                {
                    b.HasOne("ObservatorioApi.Models.Deputado", "Deputado")
                        .WithOne("PerfilAnalise")
                        .HasForeignKey("ObservatorioApi.Models.PerfilAnalise", "DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Deputado", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("PerfilAnalise");
                });
#pragma warning restore 612, 618
        }
    }
}
