// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObservatorioApi.Data;

#nullable disable

namespace ObservatorioApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702200101_AddAtuacaoParlamentar")]
    partial class AddAtuacaoParlamentar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObservatorioApi.Models.AtuacaoParlamentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AusenciasJustificadasComissoes")
                        .HasColumnType("integer");

                    b.Property<int>("AusenciasJustificadasPlenario")
                        .HasColumnType("integer");

                    b.Property<int>("AusenciasNaoJustificadasComissoes")
                        .HasColumnType("integer");

                    b.Property<int>("AusenciasNaoJustificadasPlenario")
                        .HasColumnType("integer");

                    b.Property<string>("ComissoesSuplente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComissoesTitular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeputadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Discursos")
                        .HasColumnType("integer");

                    b.Property<int>("PresencasComissoes")
                        .HasColumnType("integer");

                    b.Property<int>("PresencasPlenario")
                        .HasColumnType("integer");

                    b.Property<int>("Propostas")
                        .HasColumnType("integer");

                    b.Property<int>("PropostasAutoria")
                        .HasColumnType("integer");

                    b.Property<int>("PropostasRelatadas")
                        .HasColumnType("integer");

                    b.Property<int>("Votacoes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoId")
                        .IsUnique();

                    b.ToTable("AtuacoesParlamentares");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Deputado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCamara")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeEleitoral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiglaPartido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiglaUf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCamara")
                        .IsUnique();

                    b.ToTable("Deputados");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataDoc")
                        .HasColumnType("date");

                    b.Property<int>("DeputadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDespesa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("ObservatorioApi.Models.PerfilAnalise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeputadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeputadoId")
                        .IsUnique();

                    b.ToTable("PerfisAnalise");
                });

            modelBuilder.Entity("ObservatorioApi.Models.AtuacaoParlamentar", b =>
                {
                    b.HasOne("ObservatorioApi.Models.Deputado", "Deputado")
                        .WithOne("AtuacaoParlamentar")
                        .HasForeignKey("ObservatorioApi.Models.AtuacaoParlamentar", "DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Despesa", b =>
                {
                    b.HasOne("ObservatorioApi.Models.Deputado", "Deputado")
                        .WithMany("Despesas")
                        .HasForeignKey("DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("ObservatorioApi.Models.PerfilAnalise", b =>
                {
                    b.HasOne("ObservatorioApi.Models.Deputado", "Deputado")
                        .WithOne("PerfilAnalise")
                        .HasForeignKey("ObservatorioApi.Models.PerfilAnalise", "DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("ObservatorioApi.Models.Deputado", b =>
                {
                    b.Navigation("AtuacaoParlamentar");

                    b.Navigation("Despesas");

                    b.Navigation("PerfilAnalise");
                });
#pragma warning restore 612, 618
        }
    }
}
